apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: gamingzone
data:
  AUTH_DB_NAME: "gamingzone_auth"
  AUTH_DB_USER: "auth_user"
  CATALOG_DB_NAME: "gamingzone_catalog"
  CATALOG_DB_USER: "catalog_user"
  INVENTORY_DB_NAME: "gamingzone_inventory"
  INVENTORY_DB_USER: "inventory_user"
  ORDER_DB_NAME: "gamingzone_order"
  ORDER_DB_USER: "order_user"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: gamingzone
data:
  KAFKA_BROKER_1: "kafka-1:9092"
  KAFKA_BROKER_2: "kafka-2:9093"
  KAFKA_BROKER_3: "kafka-3:9094"
  ZOOKEEPER_CONNECT: "zookeeper:2181"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: gamingzone
data:
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
