apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: gamingzone
type: Opaque
stringData:
  AUTH_DB_PASSWORD: "change_me_auth_password"
  CATALOG_DB_PASSWORD: "change_me_catalog_password"
  INVENTORY_DB_PASSWORD: "change_me_inventory_password"
  ORDER_DB_PASSWORD: "change_me_order_password"
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: gamingzone
type: Opaque
stringData:
  REDIS_PASSWORD: "change_me_redis_password"
