apiVersion: v1
kind: ConfigMap
metadata:
  name: services-config
  namespace: gamingzone
data:
  NODE_ENV: production
  API_GATEWAY_PORT: "4000"
  AUTH_SERVICE_PORT: "4001"
  CATALOG_SERVICE_PORT: "4002"
  INVENTORY_SERVICE_PORT: "4003"
  CART_SERVICE_PORT: "4004"
  ORDER_SERVICE_PORT: "4005"
  PAYMENT_SERVICE_PORT: "4006"
  NOTIFICATION_SERVICE_PORT: "4007"
  USER_PROFILE_SERVICE_PORT: "4008"
  REVIEW_SERVICE_PORT: "4009"
  SEARCH_SERVICE_PORT: "4010"
  ANALYTICS_SERVICE_PORT: "4011"
